"""File revision

Revision ID: 3fcc586037e2
Revises: c251c2c08014
Create Date: 2025-11-26 12:05:14.328562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fcc586037e2'
down_revision: Union[str, Sequence[str], None] = 'c251c2c08014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('path', sa.String(), nullable=False))
    op.add_column('files', sa.Column('mime_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'mime_type')
    op.drop_column('files', 'path')
    # ### end Alembic commands ###
